// Store the state of each user
const userStates = {};

// Define possible states
const STATES = {
  AWAITING_NAME: "AWAITING_NAME",
  AWAITING_PHONE: "AWAITING_PHONE",
  AWAITING_FROM_WHERE: "AWAITING_FROM_WHERE",
  AWAITING_SCHOOL: "AWAITING_SCHOOL",
  AWAITING_GRADE: "AWAITING_GRADE",
  AWAITING_DATE_OF_BIRTH: "AWAITING_DATE_OF_BIRTH",
  AWAITING_ADDITIONAL_PHONE: "AWAITING_ADDITIONAL_PHONE",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION", // New confirmation step
  COMPLETED: "COMPLETED",
};

module.exports = { userStates, STATES };
